services:
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"

  streamlit:
    build: .
    container_name: student-app
    depends_on:
      - mysql
    ports:
      - "8501:8501"